### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by sambhav2612** [sambhav2612/SortingAlgorithms.cpp#2]
Please help in improving the readability of the repository by writing it's correct description inside README.md file.

Please comment here so I can assign it to you on first come basis. Add yourself into CONTRIBUTORS.md under the following format: 

```
- <Your name>[<(@Your GitHub username)>](<Your profile link>)

For example: 

- Sambhav Jain [(@sambhav2612)](https://github.com/sambhav2612)
```

Thanks for stopping by.

**Comment by ajloria** [comment]
@sambhav2612 I'd like to work on this. Could you please assign me this? Thanks.

**Comment by sambhav2612** [comment]
@ajloria you've been assigned. thanks.
